// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoverCommand.proto

#include "RoverCommand.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR RoverCommand::RoverCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stamp_)*/nullptr
  , /*decltype(_impl_.motion_mode_)*/0u
  , /*decltype(_impl_.linear_x_)*/0
  , /*decltype(_impl_.linear_y_)*/0
  , /*decltype(_impl_.linear_z_)*/0
  , /*decltype(_impl_.angular_x_)*/0
  , /*decltype(_impl_.angular_y_)*/0
  , /*decltype(_impl_.angular_z_)*/0
  , /*decltype(_impl_.headlights_on_)*/false
  , /*decltype(_impl_.led_strip_on_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoverCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoverCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoverCommandDefaultTypeInternal() {}
  union {
    RoverCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoverCommandDefaultTypeInternal _RoverCommand_default_instance_;
static ::_pb::Metadata file_level_metadata_RoverCommand_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_RoverCommand_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_RoverCommand_2eproto = nullptr;

const uint32_t TableStruct_RoverCommand_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.stamp_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.motion_mode_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.linear_x_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.linear_y_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.linear_z_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.angular_x_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.angular_y_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.angular_z_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.headlights_on_),
  PROTOBUF_FIELD_OFFSET(::RoverCommand, _impl_.led_strip_on_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::RoverCommand)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_RoverCommand_default_instance_._instance,
};

const char descriptor_table_protodef_RoverCommand_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022RoverCommand.proto\032\037google/protobuf/ti"
  "mestamp.proto\"\352\001\n\014RoverCommand\022)\n\005stamp\030"
  "\001 \001(\0132\032.google.protobuf.Timestamp\022\023\n\013mot"
  "ion_mode\030\002 \001(\r\022\020\n\010linear_x\030\003 \001(\002\022\020\n\010line"
  "ar_y\030\004 \001(\002\022\020\n\010linear_z\030\005 \001(\002\022\021\n\tangular_"
  "x\030\006 \001(\002\022\021\n\tangular_y\030\007 \001(\002\022\021\n\tangular_z\030"
  "\010 \001(\002\022\025\n\rheadlights_on\030\t \001(\010\022\024\n\014led_stri"
  "p_on\030\n \001(\010b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_RoverCommand_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_RoverCommand_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RoverCommand_2eproto = {
    false, false, 298, descriptor_table_protodef_RoverCommand_2eproto,
    "RoverCommand.proto",
    &descriptor_table_RoverCommand_2eproto_once, descriptor_table_RoverCommand_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_RoverCommand_2eproto::offsets,
    file_level_metadata_RoverCommand_2eproto, file_level_enum_descriptors_RoverCommand_2eproto,
    file_level_service_descriptors_RoverCommand_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RoverCommand_2eproto_getter() {
  return &descriptor_table_RoverCommand_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RoverCommand_2eproto(&descriptor_table_RoverCommand_2eproto);

// ===================================================================

class RoverCommand::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& stamp(const RoverCommand* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
RoverCommand::_Internal::stamp(const RoverCommand* msg) {
  return *msg->_impl_.stamp_;
}
void RoverCommand::clear_stamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.stamp_ != nullptr) {
    delete _impl_.stamp_;
  }
  _impl_.stamp_ = nullptr;
}
RoverCommand::RoverCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RoverCommand)
}
RoverCommand::RoverCommand(const RoverCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoverCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stamp_){nullptr}
    , decltype(_impl_.motion_mode_){}
    , decltype(_impl_.linear_x_){}
    , decltype(_impl_.linear_y_){}
    , decltype(_impl_.linear_z_){}
    , decltype(_impl_.angular_x_){}
    , decltype(_impl_.angular_y_){}
    , decltype(_impl_.angular_z_){}
    , decltype(_impl_.headlights_on_){}
    , decltype(_impl_.led_strip_on_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_stamp()) {
    _this->_impl_.stamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.stamp_);
  }
  ::memcpy(&_impl_.motion_mode_, &from._impl_.motion_mode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.led_strip_on_) -
    reinterpret_cast<char*>(&_impl_.motion_mode_)) + sizeof(_impl_.led_strip_on_));
  // @@protoc_insertion_point(copy_constructor:RoverCommand)
}

inline void RoverCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stamp_){nullptr}
    , decltype(_impl_.motion_mode_){0u}
    , decltype(_impl_.linear_x_){0}
    , decltype(_impl_.linear_y_){0}
    , decltype(_impl_.linear_z_){0}
    , decltype(_impl_.angular_x_){0}
    , decltype(_impl_.angular_y_){0}
    , decltype(_impl_.angular_z_){0}
    , decltype(_impl_.headlights_on_){false}
    , decltype(_impl_.led_strip_on_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RoverCommand::~RoverCommand() {
  // @@protoc_insertion_point(destructor:RoverCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoverCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.stamp_;
}

void RoverCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoverCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:RoverCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.stamp_ != nullptr) {
    delete _impl_.stamp_;
  }
  _impl_.stamp_ = nullptr;
  ::memset(&_impl_.motion_mode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.led_strip_on_) -
      reinterpret_cast<char*>(&_impl_.motion_mode_)) + sizeof(_impl_.led_strip_on_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoverCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp stamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_stamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 motion_mode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.motion_mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float linear_x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.linear_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float linear_y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.linear_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float linear_z = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.linear_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float angular_x = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.angular_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float angular_y = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.angular_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float angular_z = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.angular_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool headlights_on = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.headlights_on_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool led_strip_on = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.led_strip_on_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoverCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RoverCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp stamp = 1;
  if (this->_internal_has_stamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::stamp(this),
        _Internal::stamp(this).GetCachedSize(), target, stream);
  }

  // uint32 motion_mode = 2;
  if (this->_internal_motion_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_motion_mode(), target);
  }

  // float linear_x = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_x = this->_internal_linear_x();
  uint32_t raw_linear_x;
  memcpy(&raw_linear_x, &tmp_linear_x, sizeof(tmp_linear_x));
  if (raw_linear_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_linear_x(), target);
  }

  // float linear_y = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_y = this->_internal_linear_y();
  uint32_t raw_linear_y;
  memcpy(&raw_linear_y, &tmp_linear_y, sizeof(tmp_linear_y));
  if (raw_linear_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_linear_y(), target);
  }

  // float linear_z = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_z = this->_internal_linear_z();
  uint32_t raw_linear_z;
  memcpy(&raw_linear_z, &tmp_linear_z, sizeof(tmp_linear_z));
  if (raw_linear_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_linear_z(), target);
  }

  // float angular_x = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_x = this->_internal_angular_x();
  uint32_t raw_angular_x;
  memcpy(&raw_angular_x, &tmp_angular_x, sizeof(tmp_angular_x));
  if (raw_angular_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_angular_x(), target);
  }

  // float angular_y = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_y = this->_internal_angular_y();
  uint32_t raw_angular_y;
  memcpy(&raw_angular_y, &tmp_angular_y, sizeof(tmp_angular_y));
  if (raw_angular_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_angular_y(), target);
  }

  // float angular_z = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_z = this->_internal_angular_z();
  uint32_t raw_angular_z;
  memcpy(&raw_angular_z, &tmp_angular_z, sizeof(tmp_angular_z));
  if (raw_angular_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_angular_z(), target);
  }

  // bool headlights_on = 9;
  if (this->_internal_headlights_on() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(9, this->_internal_headlights_on(), target);
  }

  // bool led_strip_on = 10;
  if (this->_internal_led_strip_on() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(10, this->_internal_led_strip_on(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RoverCommand)
  return target;
}

size_t RoverCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RoverCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp stamp = 1;
  if (this->_internal_has_stamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.stamp_);
  }

  // uint32 motion_mode = 2;
  if (this->_internal_motion_mode() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_motion_mode());
  }

  // float linear_x = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_x = this->_internal_linear_x();
  uint32_t raw_linear_x;
  memcpy(&raw_linear_x, &tmp_linear_x, sizeof(tmp_linear_x));
  if (raw_linear_x != 0) {
    total_size += 1 + 4;
  }

  // float linear_y = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_y = this->_internal_linear_y();
  uint32_t raw_linear_y;
  memcpy(&raw_linear_y, &tmp_linear_y, sizeof(tmp_linear_y));
  if (raw_linear_y != 0) {
    total_size += 1 + 4;
  }

  // float linear_z = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_z = this->_internal_linear_z();
  uint32_t raw_linear_z;
  memcpy(&raw_linear_z, &tmp_linear_z, sizeof(tmp_linear_z));
  if (raw_linear_z != 0) {
    total_size += 1 + 4;
  }

  // float angular_x = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_x = this->_internal_angular_x();
  uint32_t raw_angular_x;
  memcpy(&raw_angular_x, &tmp_angular_x, sizeof(tmp_angular_x));
  if (raw_angular_x != 0) {
    total_size += 1 + 4;
  }

  // float angular_y = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_y = this->_internal_angular_y();
  uint32_t raw_angular_y;
  memcpy(&raw_angular_y, &tmp_angular_y, sizeof(tmp_angular_y));
  if (raw_angular_y != 0) {
    total_size += 1 + 4;
  }

  // float angular_z = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_z = this->_internal_angular_z();
  uint32_t raw_angular_z;
  memcpy(&raw_angular_z, &tmp_angular_z, sizeof(tmp_angular_z));
  if (raw_angular_z != 0) {
    total_size += 1 + 4;
  }

  // bool headlights_on = 9;
  if (this->_internal_headlights_on() != 0) {
    total_size += 1 + 1;
  }

  // bool led_strip_on = 10;
  if (this->_internal_led_strip_on() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoverCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoverCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoverCommand::GetClassData() const { return &_class_data_; }


void RoverCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoverCommand*>(&to_msg);
  auto& from = static_cast<const RoverCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RoverCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_stamp()) {
    _this->_internal_mutable_stamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_stamp());
  }
  if (from._internal_motion_mode() != 0) {
    _this->_internal_set_motion_mode(from._internal_motion_mode());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_x = from._internal_linear_x();
  uint32_t raw_linear_x;
  memcpy(&raw_linear_x, &tmp_linear_x, sizeof(tmp_linear_x));
  if (raw_linear_x != 0) {
    _this->_internal_set_linear_x(from._internal_linear_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_y = from._internal_linear_y();
  uint32_t raw_linear_y;
  memcpy(&raw_linear_y, &tmp_linear_y, sizeof(tmp_linear_y));
  if (raw_linear_y != 0) {
    _this->_internal_set_linear_y(from._internal_linear_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_linear_z = from._internal_linear_z();
  uint32_t raw_linear_z;
  memcpy(&raw_linear_z, &tmp_linear_z, sizeof(tmp_linear_z));
  if (raw_linear_z != 0) {
    _this->_internal_set_linear_z(from._internal_linear_z());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_x = from._internal_angular_x();
  uint32_t raw_angular_x;
  memcpy(&raw_angular_x, &tmp_angular_x, sizeof(tmp_angular_x));
  if (raw_angular_x != 0) {
    _this->_internal_set_angular_x(from._internal_angular_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_y = from._internal_angular_y();
  uint32_t raw_angular_y;
  memcpy(&raw_angular_y, &tmp_angular_y, sizeof(tmp_angular_y));
  if (raw_angular_y != 0) {
    _this->_internal_set_angular_y(from._internal_angular_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_angular_z = from._internal_angular_z();
  uint32_t raw_angular_z;
  memcpy(&raw_angular_z, &tmp_angular_z, sizeof(tmp_angular_z));
  if (raw_angular_z != 0) {
    _this->_internal_set_angular_z(from._internal_angular_z());
  }
  if (from._internal_headlights_on() != 0) {
    _this->_internal_set_headlights_on(from._internal_headlights_on());
  }
  if (from._internal_led_strip_on() != 0) {
    _this->_internal_set_led_strip_on(from._internal_led_strip_on());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoverCommand::CopyFrom(const RoverCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RoverCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoverCommand::IsInitialized() const {
  return true;
}

void RoverCommand::InternalSwap(RoverCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RoverCommand, _impl_.led_strip_on_)
      + sizeof(RoverCommand::_impl_.led_strip_on_)
      - PROTOBUF_FIELD_OFFSET(RoverCommand, _impl_.stamp_)>(
          reinterpret_cast<char*>(&_impl_.stamp_),
          reinterpret_cast<char*>(&other->_impl_.stamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RoverCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RoverCommand_2eproto_getter, &descriptor_table_RoverCommand_2eproto_once,
      file_level_metadata_RoverCommand_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::RoverCommand*
Arena::CreateMaybeMessage< ::RoverCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RoverCommand >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
