// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoverCommand.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RoverCommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RoverCommand_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RoverCommand_2eproto;
class RoverCommand;
struct RoverCommandDefaultTypeInternal;
extern RoverCommandDefaultTypeInternal _RoverCommand_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RoverCommand* Arena::CreateMaybeMessage<::RoverCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class RoverCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoverCommand) */ {
 public:
  inline RoverCommand() : RoverCommand(nullptr) {}
  ~RoverCommand() override;
  explicit PROTOBUF_CONSTEXPR RoverCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoverCommand(const RoverCommand& from);
  RoverCommand(RoverCommand&& from) noexcept
    : RoverCommand() {
    *this = ::std::move(from);
  }

  inline RoverCommand& operator=(const RoverCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoverCommand& operator=(RoverCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoverCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoverCommand* internal_default_instance() {
    return reinterpret_cast<const RoverCommand*>(
               &_RoverCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoverCommand& a, RoverCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(RoverCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoverCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoverCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoverCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoverCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoverCommand& from) {
    RoverCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoverCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoverCommand";
  }
  protected:
  explicit RoverCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStampFieldNumber = 1,
    kSequenceFieldNumber = 2,
    kWheelFlFieldNumber = 3,
    kWheelMlFieldNumber = 4,
    kWheelRlFieldNumber = 5,
    kWheelFrFieldNumber = 6,
    kWheelMrFieldNumber = 7,
    kWheelRrFieldNumber = 8,
    kSteerFlFieldNumber = 9,
    kSteerRlFieldNumber = 10,
    kSteerFrFieldNumber = 11,
    kSteerRrFieldNumber = 12,
    kHeadlightsOnFieldNumber = 13,
    kLedStripOnFieldNumber = 14,
    kEnableMotorsFieldNumber = 15,
    kEstopFieldNumber = 16,
  };
  // .google.protobuf.Timestamp stamp = 1;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& stamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_stamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_stamp();
  void set_allocated_stamp(::PROTOBUF_NAMESPACE_ID::Timestamp* stamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_stamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_stamp();

  // uint32 sequence = 2;
  void clear_sequence();
  uint32_t sequence() const;
  void set_sequence(uint32_t value);
  private:
  uint32_t _internal_sequence() const;
  void _internal_set_sequence(uint32_t value);
  public:

  // float wheel_fl = 3;
  void clear_wheel_fl();
  float wheel_fl() const;
  void set_wheel_fl(float value);
  private:
  float _internal_wheel_fl() const;
  void _internal_set_wheel_fl(float value);
  public:

  // float wheel_ml = 4;
  void clear_wheel_ml();
  float wheel_ml() const;
  void set_wheel_ml(float value);
  private:
  float _internal_wheel_ml() const;
  void _internal_set_wheel_ml(float value);
  public:

  // float wheel_rl = 5;
  void clear_wheel_rl();
  float wheel_rl() const;
  void set_wheel_rl(float value);
  private:
  float _internal_wheel_rl() const;
  void _internal_set_wheel_rl(float value);
  public:

  // float wheel_fr = 6;
  void clear_wheel_fr();
  float wheel_fr() const;
  void set_wheel_fr(float value);
  private:
  float _internal_wheel_fr() const;
  void _internal_set_wheel_fr(float value);
  public:

  // float wheel_mr = 7;
  void clear_wheel_mr();
  float wheel_mr() const;
  void set_wheel_mr(float value);
  private:
  float _internal_wheel_mr() const;
  void _internal_set_wheel_mr(float value);
  public:

  // float wheel_rr = 8;
  void clear_wheel_rr();
  float wheel_rr() const;
  void set_wheel_rr(float value);
  private:
  float _internal_wheel_rr() const;
  void _internal_set_wheel_rr(float value);
  public:

  // float steer_fl = 9;
  void clear_steer_fl();
  float steer_fl() const;
  void set_steer_fl(float value);
  private:
  float _internal_steer_fl() const;
  void _internal_set_steer_fl(float value);
  public:

  // float steer_rl = 10;
  void clear_steer_rl();
  float steer_rl() const;
  void set_steer_rl(float value);
  private:
  float _internal_steer_rl() const;
  void _internal_set_steer_rl(float value);
  public:

  // float steer_fr = 11;
  void clear_steer_fr();
  float steer_fr() const;
  void set_steer_fr(float value);
  private:
  float _internal_steer_fr() const;
  void _internal_set_steer_fr(float value);
  public:

  // float steer_rr = 12;
  void clear_steer_rr();
  float steer_rr() const;
  void set_steer_rr(float value);
  private:
  float _internal_steer_rr() const;
  void _internal_set_steer_rr(float value);
  public:

  // bool headlights_on = 13;
  void clear_headlights_on();
  bool headlights_on() const;
  void set_headlights_on(bool value);
  private:
  bool _internal_headlights_on() const;
  void _internal_set_headlights_on(bool value);
  public:

  // bool led_strip_on = 14;
  void clear_led_strip_on();
  bool led_strip_on() const;
  void set_led_strip_on(bool value);
  private:
  bool _internal_led_strip_on() const;
  void _internal_set_led_strip_on(bool value);
  public:

  // bool enable_motors = 15;
  void clear_enable_motors();
  bool enable_motors() const;
  void set_enable_motors(bool value);
  private:
  bool _internal_enable_motors() const;
  void _internal_set_enable_motors(bool value);
  public:

  // bool estop = 16;
  void clear_estop();
  bool estop() const;
  void set_estop(bool value);
  private:
  bool _internal_estop() const;
  void _internal_set_estop(bool value);
  public:

  // @@protoc_insertion_point(class_scope:RoverCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp_;
    uint32_t sequence_;
    float wheel_fl_;
    float wheel_ml_;
    float wheel_rl_;
    float wheel_fr_;
    float wheel_mr_;
    float wheel_rr_;
    float steer_fl_;
    float steer_rl_;
    float steer_fr_;
    float steer_rr_;
    bool headlights_on_;
    bool led_strip_on_;
    bool enable_motors_;
    bool estop_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RoverCommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoverCommand

// .google.protobuf.Timestamp stamp = 1;
inline bool RoverCommand::_internal_has_stamp() const {
  return this != internal_default_instance() && _impl_.stamp_ != nullptr;
}
inline bool RoverCommand::has_stamp() const {
  return _internal_has_stamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& RoverCommand::_internal_stamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.stamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& RoverCommand::stamp() const {
  // @@protoc_insertion_point(field_get:RoverCommand.stamp)
  return _internal_stamp();
}
inline void RoverCommand::unsafe_arena_set_allocated_stamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stamp_);
  }
  _impl_.stamp_ = stamp;
  if (stamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RoverCommand.stamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::release_stamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:RoverCommand.stamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::_internal_mutable_stamp() {
  
  if (_impl_.stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.stamp_ = p;
  }
  return _impl_.stamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::mutable_stamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_stamp();
  // @@protoc_insertion_point(field_mutable:RoverCommand.stamp)
  return _msg;
}
inline void RoverCommand::set_allocated_stamp(::PROTOBUF_NAMESPACE_ID::Timestamp* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stamp_);
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp));
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:RoverCommand.stamp)
}

// uint32 sequence = 2;
inline void RoverCommand::clear_sequence() {
  _impl_.sequence_ = 0u;
}
inline uint32_t RoverCommand::_internal_sequence() const {
  return _impl_.sequence_;
}
inline uint32_t RoverCommand::sequence() const {
  // @@protoc_insertion_point(field_get:RoverCommand.sequence)
  return _internal_sequence();
}
inline void RoverCommand::_internal_set_sequence(uint32_t value) {
  
  _impl_.sequence_ = value;
}
inline void RoverCommand::set_sequence(uint32_t value) {
  _internal_set_sequence(value);
  // @@protoc_insertion_point(field_set:RoverCommand.sequence)
}

// float wheel_fl = 3;
inline void RoverCommand::clear_wheel_fl() {
  _impl_.wheel_fl_ = 0;
}
inline float RoverCommand::_internal_wheel_fl() const {
  return _impl_.wheel_fl_;
}
inline float RoverCommand::wheel_fl() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_fl)
  return _internal_wheel_fl();
}
inline void RoverCommand::_internal_set_wheel_fl(float value) {
  
  _impl_.wheel_fl_ = value;
}
inline void RoverCommand::set_wheel_fl(float value) {
  _internal_set_wheel_fl(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_fl)
}

// float wheel_ml = 4;
inline void RoverCommand::clear_wheel_ml() {
  _impl_.wheel_ml_ = 0;
}
inline float RoverCommand::_internal_wheel_ml() const {
  return _impl_.wheel_ml_;
}
inline float RoverCommand::wheel_ml() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_ml)
  return _internal_wheel_ml();
}
inline void RoverCommand::_internal_set_wheel_ml(float value) {
  
  _impl_.wheel_ml_ = value;
}
inline void RoverCommand::set_wheel_ml(float value) {
  _internal_set_wheel_ml(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_ml)
}

// float wheel_rl = 5;
inline void RoverCommand::clear_wheel_rl() {
  _impl_.wheel_rl_ = 0;
}
inline float RoverCommand::_internal_wheel_rl() const {
  return _impl_.wheel_rl_;
}
inline float RoverCommand::wheel_rl() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_rl)
  return _internal_wheel_rl();
}
inline void RoverCommand::_internal_set_wheel_rl(float value) {
  
  _impl_.wheel_rl_ = value;
}
inline void RoverCommand::set_wheel_rl(float value) {
  _internal_set_wheel_rl(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_rl)
}

// float wheel_fr = 6;
inline void RoverCommand::clear_wheel_fr() {
  _impl_.wheel_fr_ = 0;
}
inline float RoverCommand::_internal_wheel_fr() const {
  return _impl_.wheel_fr_;
}
inline float RoverCommand::wheel_fr() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_fr)
  return _internal_wheel_fr();
}
inline void RoverCommand::_internal_set_wheel_fr(float value) {
  
  _impl_.wheel_fr_ = value;
}
inline void RoverCommand::set_wheel_fr(float value) {
  _internal_set_wheel_fr(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_fr)
}

// float wheel_mr = 7;
inline void RoverCommand::clear_wheel_mr() {
  _impl_.wheel_mr_ = 0;
}
inline float RoverCommand::_internal_wheel_mr() const {
  return _impl_.wheel_mr_;
}
inline float RoverCommand::wheel_mr() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_mr)
  return _internal_wheel_mr();
}
inline void RoverCommand::_internal_set_wheel_mr(float value) {
  
  _impl_.wheel_mr_ = value;
}
inline void RoverCommand::set_wheel_mr(float value) {
  _internal_set_wheel_mr(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_mr)
}

// float wheel_rr = 8;
inline void RoverCommand::clear_wheel_rr() {
  _impl_.wheel_rr_ = 0;
}
inline float RoverCommand::_internal_wheel_rr() const {
  return _impl_.wheel_rr_;
}
inline float RoverCommand::wheel_rr() const {
  // @@protoc_insertion_point(field_get:RoverCommand.wheel_rr)
  return _internal_wheel_rr();
}
inline void RoverCommand::_internal_set_wheel_rr(float value) {
  
  _impl_.wheel_rr_ = value;
}
inline void RoverCommand::set_wheel_rr(float value) {
  _internal_set_wheel_rr(value);
  // @@protoc_insertion_point(field_set:RoverCommand.wheel_rr)
}

// float steer_fl = 9;
inline void RoverCommand::clear_steer_fl() {
  _impl_.steer_fl_ = 0;
}
inline float RoverCommand::_internal_steer_fl() const {
  return _impl_.steer_fl_;
}
inline float RoverCommand::steer_fl() const {
  // @@protoc_insertion_point(field_get:RoverCommand.steer_fl)
  return _internal_steer_fl();
}
inline void RoverCommand::_internal_set_steer_fl(float value) {
  
  _impl_.steer_fl_ = value;
}
inline void RoverCommand::set_steer_fl(float value) {
  _internal_set_steer_fl(value);
  // @@protoc_insertion_point(field_set:RoverCommand.steer_fl)
}

// float steer_rl = 10;
inline void RoverCommand::clear_steer_rl() {
  _impl_.steer_rl_ = 0;
}
inline float RoverCommand::_internal_steer_rl() const {
  return _impl_.steer_rl_;
}
inline float RoverCommand::steer_rl() const {
  // @@protoc_insertion_point(field_get:RoverCommand.steer_rl)
  return _internal_steer_rl();
}
inline void RoverCommand::_internal_set_steer_rl(float value) {
  
  _impl_.steer_rl_ = value;
}
inline void RoverCommand::set_steer_rl(float value) {
  _internal_set_steer_rl(value);
  // @@protoc_insertion_point(field_set:RoverCommand.steer_rl)
}

// float steer_fr = 11;
inline void RoverCommand::clear_steer_fr() {
  _impl_.steer_fr_ = 0;
}
inline float RoverCommand::_internal_steer_fr() const {
  return _impl_.steer_fr_;
}
inline float RoverCommand::steer_fr() const {
  // @@protoc_insertion_point(field_get:RoverCommand.steer_fr)
  return _internal_steer_fr();
}
inline void RoverCommand::_internal_set_steer_fr(float value) {
  
  _impl_.steer_fr_ = value;
}
inline void RoverCommand::set_steer_fr(float value) {
  _internal_set_steer_fr(value);
  // @@protoc_insertion_point(field_set:RoverCommand.steer_fr)
}

// float steer_rr = 12;
inline void RoverCommand::clear_steer_rr() {
  _impl_.steer_rr_ = 0;
}
inline float RoverCommand::_internal_steer_rr() const {
  return _impl_.steer_rr_;
}
inline float RoverCommand::steer_rr() const {
  // @@protoc_insertion_point(field_get:RoverCommand.steer_rr)
  return _internal_steer_rr();
}
inline void RoverCommand::_internal_set_steer_rr(float value) {
  
  _impl_.steer_rr_ = value;
}
inline void RoverCommand::set_steer_rr(float value) {
  _internal_set_steer_rr(value);
  // @@protoc_insertion_point(field_set:RoverCommand.steer_rr)
}

// bool headlights_on = 13;
inline void RoverCommand::clear_headlights_on() {
  _impl_.headlights_on_ = false;
}
inline bool RoverCommand::_internal_headlights_on() const {
  return _impl_.headlights_on_;
}
inline bool RoverCommand::headlights_on() const {
  // @@protoc_insertion_point(field_get:RoverCommand.headlights_on)
  return _internal_headlights_on();
}
inline void RoverCommand::_internal_set_headlights_on(bool value) {
  
  _impl_.headlights_on_ = value;
}
inline void RoverCommand::set_headlights_on(bool value) {
  _internal_set_headlights_on(value);
  // @@protoc_insertion_point(field_set:RoverCommand.headlights_on)
}

// bool led_strip_on = 14;
inline void RoverCommand::clear_led_strip_on() {
  _impl_.led_strip_on_ = false;
}
inline bool RoverCommand::_internal_led_strip_on() const {
  return _impl_.led_strip_on_;
}
inline bool RoverCommand::led_strip_on() const {
  // @@protoc_insertion_point(field_get:RoverCommand.led_strip_on)
  return _internal_led_strip_on();
}
inline void RoverCommand::_internal_set_led_strip_on(bool value) {
  
  _impl_.led_strip_on_ = value;
}
inline void RoverCommand::set_led_strip_on(bool value) {
  _internal_set_led_strip_on(value);
  // @@protoc_insertion_point(field_set:RoverCommand.led_strip_on)
}

// bool enable_motors = 15;
inline void RoverCommand::clear_enable_motors() {
  _impl_.enable_motors_ = false;
}
inline bool RoverCommand::_internal_enable_motors() const {
  return _impl_.enable_motors_;
}
inline bool RoverCommand::enable_motors() const {
  // @@protoc_insertion_point(field_get:RoverCommand.enable_motors)
  return _internal_enable_motors();
}
inline void RoverCommand::_internal_set_enable_motors(bool value) {
  
  _impl_.enable_motors_ = value;
}
inline void RoverCommand::set_enable_motors(bool value) {
  _internal_set_enable_motors(value);
  // @@protoc_insertion_point(field_set:RoverCommand.enable_motors)
}

// bool estop = 16;
inline void RoverCommand::clear_estop() {
  _impl_.estop_ = false;
}
inline bool RoverCommand::_internal_estop() const {
  return _impl_.estop_;
}
inline bool RoverCommand::estop() const {
  // @@protoc_insertion_point(field_get:RoverCommand.estop)
  return _internal_estop();
}
inline void RoverCommand::_internal_set_estop(bool value) {
  
  _impl_.estop_ = value;
}
inline void RoverCommand::set_estop(bool value) {
  _internal_set_estop(value);
  // @@protoc_insertion_point(field_set:RoverCommand.estop)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto
