// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoverCommand.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RoverCommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RoverCommand_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RoverCommand_2eproto;
class RoverCommand;
struct RoverCommandDefaultTypeInternal;
extern RoverCommandDefaultTypeInternal _RoverCommand_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RoverCommand* Arena::CreateMaybeMessage<::RoverCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class RoverCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoverCommand) */ {
 public:
  inline RoverCommand() : RoverCommand(nullptr) {}
  ~RoverCommand() override;
  explicit PROTOBUF_CONSTEXPR RoverCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoverCommand(const RoverCommand& from);
  RoverCommand(RoverCommand&& from) noexcept
    : RoverCommand() {
    *this = ::std::move(from);
  }

  inline RoverCommand& operator=(const RoverCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoverCommand& operator=(RoverCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoverCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoverCommand* internal_default_instance() {
    return reinterpret_cast<const RoverCommand*>(
               &_RoverCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoverCommand& a, RoverCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(RoverCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoverCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoverCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoverCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoverCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoverCommand& from) {
    RoverCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoverCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoverCommand";
  }
  protected:
  explicit RoverCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStampFieldNumber = 1,
    kMotionModeFieldNumber = 2,
    kLinearXFieldNumber = 3,
    kLinearYFieldNumber = 4,
    kLinearZFieldNumber = 5,
    kAngularXFieldNumber = 6,
    kAngularYFieldNumber = 7,
    kAngularZFieldNumber = 8,
    kHeadlightsOnFieldNumber = 9,
    kLedStripOnFieldNumber = 10,
  };
  // .google.protobuf.Timestamp stamp = 1;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& stamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_stamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_stamp();
  void set_allocated_stamp(::PROTOBUF_NAMESPACE_ID::Timestamp* stamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_stamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_stamp();

  // uint32 motion_mode = 2;
  void clear_motion_mode();
  uint32_t motion_mode() const;
  void set_motion_mode(uint32_t value);
  private:
  uint32_t _internal_motion_mode() const;
  void _internal_set_motion_mode(uint32_t value);
  public:

  // float linear_x = 3;
  void clear_linear_x();
  float linear_x() const;
  void set_linear_x(float value);
  private:
  float _internal_linear_x() const;
  void _internal_set_linear_x(float value);
  public:

  // float linear_y = 4;
  void clear_linear_y();
  float linear_y() const;
  void set_linear_y(float value);
  private:
  float _internal_linear_y() const;
  void _internal_set_linear_y(float value);
  public:

  // float linear_z = 5;
  void clear_linear_z();
  float linear_z() const;
  void set_linear_z(float value);
  private:
  float _internal_linear_z() const;
  void _internal_set_linear_z(float value);
  public:

  // float angular_x = 6;
  void clear_angular_x();
  float angular_x() const;
  void set_angular_x(float value);
  private:
  float _internal_angular_x() const;
  void _internal_set_angular_x(float value);
  public:

  // float angular_y = 7;
  void clear_angular_y();
  float angular_y() const;
  void set_angular_y(float value);
  private:
  float _internal_angular_y() const;
  void _internal_set_angular_y(float value);
  public:

  // float angular_z = 8;
  void clear_angular_z();
  float angular_z() const;
  void set_angular_z(float value);
  private:
  float _internal_angular_z() const;
  void _internal_set_angular_z(float value);
  public:

  // bool headlights_on = 9;
  void clear_headlights_on();
  bool headlights_on() const;
  void set_headlights_on(bool value);
  private:
  bool _internal_headlights_on() const;
  void _internal_set_headlights_on(bool value);
  public:

  // bool led_strip_on = 10;
  void clear_led_strip_on();
  bool led_strip_on() const;
  void set_led_strip_on(bool value);
  private:
  bool _internal_led_strip_on() const;
  void _internal_set_led_strip_on(bool value);
  public:

  // @@protoc_insertion_point(class_scope:RoverCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp_;
    uint32_t motion_mode_;
    float linear_x_;
    float linear_y_;
    float linear_z_;
    float angular_x_;
    float angular_y_;
    float angular_z_;
    bool headlights_on_;
    bool led_strip_on_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RoverCommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoverCommand

// .google.protobuf.Timestamp stamp = 1;
inline bool RoverCommand::_internal_has_stamp() const {
  return this != internal_default_instance() && _impl_.stamp_ != nullptr;
}
inline bool RoverCommand::has_stamp() const {
  return _internal_has_stamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& RoverCommand::_internal_stamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.stamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& RoverCommand::stamp() const {
  // @@protoc_insertion_point(field_get:RoverCommand.stamp)
  return _internal_stamp();
}
inline void RoverCommand::unsafe_arena_set_allocated_stamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* stamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stamp_);
  }
  _impl_.stamp_ = stamp;
  if (stamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RoverCommand.stamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::release_stamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:RoverCommand.stamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.stamp_;
  _impl_.stamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::_internal_mutable_stamp() {
  
  if (_impl_.stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.stamp_ = p;
  }
  return _impl_.stamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* RoverCommand::mutable_stamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_stamp();
  // @@protoc_insertion_point(field_mutable:RoverCommand.stamp)
  return _msg;
}
inline void RoverCommand::set_allocated_stamp(::PROTOBUF_NAMESPACE_ID::Timestamp* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stamp_);
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp));
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:RoverCommand.stamp)
}

// uint32 motion_mode = 2;
inline void RoverCommand::clear_motion_mode() {
  _impl_.motion_mode_ = 0u;
}
inline uint32_t RoverCommand::_internal_motion_mode() const {
  return _impl_.motion_mode_;
}
inline uint32_t RoverCommand::motion_mode() const {
  // @@protoc_insertion_point(field_get:RoverCommand.motion_mode)
  return _internal_motion_mode();
}
inline void RoverCommand::_internal_set_motion_mode(uint32_t value) {
  
  _impl_.motion_mode_ = value;
}
inline void RoverCommand::set_motion_mode(uint32_t value) {
  _internal_set_motion_mode(value);
  // @@protoc_insertion_point(field_set:RoverCommand.motion_mode)
}

// float linear_x = 3;
inline void RoverCommand::clear_linear_x() {
  _impl_.linear_x_ = 0;
}
inline float RoverCommand::_internal_linear_x() const {
  return _impl_.linear_x_;
}
inline float RoverCommand::linear_x() const {
  // @@protoc_insertion_point(field_get:RoverCommand.linear_x)
  return _internal_linear_x();
}
inline void RoverCommand::_internal_set_linear_x(float value) {
  
  _impl_.linear_x_ = value;
}
inline void RoverCommand::set_linear_x(float value) {
  _internal_set_linear_x(value);
  // @@protoc_insertion_point(field_set:RoverCommand.linear_x)
}

// float linear_y = 4;
inline void RoverCommand::clear_linear_y() {
  _impl_.linear_y_ = 0;
}
inline float RoverCommand::_internal_linear_y() const {
  return _impl_.linear_y_;
}
inline float RoverCommand::linear_y() const {
  // @@protoc_insertion_point(field_get:RoverCommand.linear_y)
  return _internal_linear_y();
}
inline void RoverCommand::_internal_set_linear_y(float value) {
  
  _impl_.linear_y_ = value;
}
inline void RoverCommand::set_linear_y(float value) {
  _internal_set_linear_y(value);
  // @@protoc_insertion_point(field_set:RoverCommand.linear_y)
}

// float linear_z = 5;
inline void RoverCommand::clear_linear_z() {
  _impl_.linear_z_ = 0;
}
inline float RoverCommand::_internal_linear_z() const {
  return _impl_.linear_z_;
}
inline float RoverCommand::linear_z() const {
  // @@protoc_insertion_point(field_get:RoverCommand.linear_z)
  return _internal_linear_z();
}
inline void RoverCommand::_internal_set_linear_z(float value) {
  
  _impl_.linear_z_ = value;
}
inline void RoverCommand::set_linear_z(float value) {
  _internal_set_linear_z(value);
  // @@protoc_insertion_point(field_set:RoverCommand.linear_z)
}

// float angular_x = 6;
inline void RoverCommand::clear_angular_x() {
  _impl_.angular_x_ = 0;
}
inline float RoverCommand::_internal_angular_x() const {
  return _impl_.angular_x_;
}
inline float RoverCommand::angular_x() const {
  // @@protoc_insertion_point(field_get:RoverCommand.angular_x)
  return _internal_angular_x();
}
inline void RoverCommand::_internal_set_angular_x(float value) {
  
  _impl_.angular_x_ = value;
}
inline void RoverCommand::set_angular_x(float value) {
  _internal_set_angular_x(value);
  // @@protoc_insertion_point(field_set:RoverCommand.angular_x)
}

// float angular_y = 7;
inline void RoverCommand::clear_angular_y() {
  _impl_.angular_y_ = 0;
}
inline float RoverCommand::_internal_angular_y() const {
  return _impl_.angular_y_;
}
inline float RoverCommand::angular_y() const {
  // @@protoc_insertion_point(field_get:RoverCommand.angular_y)
  return _internal_angular_y();
}
inline void RoverCommand::_internal_set_angular_y(float value) {
  
  _impl_.angular_y_ = value;
}
inline void RoverCommand::set_angular_y(float value) {
  _internal_set_angular_y(value);
  // @@protoc_insertion_point(field_set:RoverCommand.angular_y)
}

// float angular_z = 8;
inline void RoverCommand::clear_angular_z() {
  _impl_.angular_z_ = 0;
}
inline float RoverCommand::_internal_angular_z() const {
  return _impl_.angular_z_;
}
inline float RoverCommand::angular_z() const {
  // @@protoc_insertion_point(field_get:RoverCommand.angular_z)
  return _internal_angular_z();
}
inline void RoverCommand::_internal_set_angular_z(float value) {
  
  _impl_.angular_z_ = value;
}
inline void RoverCommand::set_angular_z(float value) {
  _internal_set_angular_z(value);
  // @@protoc_insertion_point(field_set:RoverCommand.angular_z)
}

// bool headlights_on = 9;
inline void RoverCommand::clear_headlights_on() {
  _impl_.headlights_on_ = false;
}
inline bool RoverCommand::_internal_headlights_on() const {
  return _impl_.headlights_on_;
}
inline bool RoverCommand::headlights_on() const {
  // @@protoc_insertion_point(field_get:RoverCommand.headlights_on)
  return _internal_headlights_on();
}
inline void RoverCommand::_internal_set_headlights_on(bool value) {
  
  _impl_.headlights_on_ = value;
}
inline void RoverCommand::set_headlights_on(bool value) {
  _internal_set_headlights_on(value);
  // @@protoc_insertion_point(field_set:RoverCommand.headlights_on)
}

// bool led_strip_on = 10;
inline void RoverCommand::clear_led_strip_on() {
  _impl_.led_strip_on_ = false;
}
inline bool RoverCommand::_internal_led_strip_on() const {
  return _impl_.led_strip_on_;
}
inline bool RoverCommand::led_strip_on() const {
  // @@protoc_insertion_point(field_get:RoverCommand.led_strip_on)
  return _internal_led_strip_on();
}
inline void RoverCommand::_internal_set_led_strip_on(bool value) {
  
  _impl_.led_strip_on_ = value;
}
inline void RoverCommand::set_led_strip_on(bool value) {
  _internal_set_led_strip_on(value);
  // @@protoc_insertion_point(field_set:RoverCommand.led_strip_on)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RoverCommand_2eproto
