/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ROVERCOMMAND_PB_H_INCLUDED
#define PB_ROVERCOMMAND_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RoverCommand {
    /* Timestamp */
    bool has_stamp;
    google_protobuf_Timestamp stamp;
    uint32_t sequence;
    /* Drive commands [-1, 1] */
    float wheel_fl;
    float wheel_ml;
    float wheel_rl;
    float wheel_fr;
    float wheel_mr;
    float wheel_rr;
    /* Steer commands [rads] */
    float steer_fl;
    float steer_rl;
    float steer_fr;
    float steer_rr;
    /* Auxiliary */
    bool headlights_on;
    bool led_strip_on;
    /* Safety */
    bool enable_motors;
    bool estop;
} RoverCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RoverCommand_init_default                {false, google_protobuf_Timestamp_init_default, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RoverCommand_init_zero                   {false, google_protobuf_Timestamp_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RoverCommand_stamp_tag                   1
#define RoverCommand_sequence_tag                2
#define RoverCommand_wheel_fl_tag                3
#define RoverCommand_wheel_ml_tag                4
#define RoverCommand_wheel_rl_tag                5
#define RoverCommand_wheel_fr_tag                6
#define RoverCommand_wheel_mr_tag                7
#define RoverCommand_wheel_rr_tag                8
#define RoverCommand_steer_fl_tag                9
#define RoverCommand_steer_rl_tag                10
#define RoverCommand_steer_fr_tag                11
#define RoverCommand_steer_rr_tag                12
#define RoverCommand_headlights_on_tag           13
#define RoverCommand_led_strip_on_tag            14
#define RoverCommand_enable_motors_tag           15
#define RoverCommand_estop_tag                   16

/* Struct field encoding specification for nanopb */
#define RoverCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stamp,             1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_fl,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_ml,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_rl,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_fr,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_mr,          7) \
X(a, STATIC,   SINGULAR, FLOAT,    wheel_rr,          8) \
X(a, STATIC,   SINGULAR, FLOAT,    steer_fl,          9) \
X(a, STATIC,   SINGULAR, FLOAT,    steer_rl,         10) \
X(a, STATIC,   SINGULAR, FLOAT,    steer_fr,         11) \
X(a, STATIC,   SINGULAR, FLOAT,    steer_rr,         12) \
X(a, STATIC,   SINGULAR, BOOL,     headlights_on,    13) \
X(a, STATIC,   SINGULAR, BOOL,     led_strip_on,     14) \
X(a, STATIC,   SINGULAR, BOOL,     enable_motors,    15) \
X(a, STATIC,   SINGULAR, BOOL,     estop,            16)
#define RoverCommand_CALLBACK NULL
#define RoverCommand_DEFAULT NULL
#define RoverCommand_stamp_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t RoverCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RoverCommand_fields &RoverCommand_msg

/* Maximum encoded size of messages (where known) */
#define ROVERCOMMAND_PB_H_MAX_SIZE               RoverCommand_size
#define RoverCommand_size                        89

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
